ilatinoamericano/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from mymessages.views import send_message,thanks
from informacion import urls
from usuarios import urls
from calificaciones import urls
from django.contrib.auth import views as auth_views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('send_message/',send_message, name="send_message"),
    url(r'profile/',include('usuarios.urls'),name='usuarios'),
    url(r'cal/',include('calificaciones.urls'),name='cali'),
    url(r'^',include('informacion.urls'),name='informacion'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usuarios/urls.py
from django.conf.urls import url
from .views import register,login_user
from django.contrib.auth import views as auth_views

urlpatterns = [
url(r'^login/$',login_user, name='login'),
url(r'^logout/$', auth_views.LogoutView.as_view(template_name='index_view.html'), name='logout'),
url('register/',register,name='register'),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import (AbstractBaseUser,BaseUserManager)
class UserManager(BaseUserManager):
    def create_user(self,email,nombre,phone,direcion,password,is_staff=False,is_superuser=False,is_active=True):
        if not email:
            raise ValueError('email es requerido')
        if not nombre:
            raise ValueError("nombre requerido")
        if not phone:
            raise ValueError("un telefono es requerido")
        if not direcion:
            raise ValueError("una direcion es requerida")
        if not password:
            raise ValueError('un password es requerido')
        user_obj=self.model(
        email=self.normalize_email(email)
        )
        user_obj.set_password(password)
        user_obj.nombre=nombre
        user_obj.phone=phone
        user_obj.direcion=direcion
        user_obj.staff=is_staff
        user_obj.superuser=is_superuser
        user_obj.active=is_active
        user_obj.save()
        return user_obj
    def create_staff(self,email,nombre,phone,direcion,password):
        user=self.create_user(email,
        nombre=nombre,
        phone=phone,
        direcion=direcion,
        staff=True,superuser=False)
        return user
    def create_superuser(self,email,nombre,phone,direcion,password,is_superuser=True,is_staff=True):
        user=self.create_user(email,
        nombre=nombre,phone=phone,password=password,
        is_staff=is_staff,
        direcion=direcion,is_superuser=True)
        return user
#the costum user
class my_user(AbstractBaseUser):
    email= models.EmailField(max_length=255,unique=True,null=False)
    staff=models.BooleanField(default=False)
    nombre=models.CharField(max_length=100)
    phone= models.CharField(max_length=100)
    direcion=models.CharField(max_length=100)
    superuser=models.BooleanField(default=False)
    USERNAME_FIELD='email'
    REQUIRED_FIELDS=['nombre','phone','direcion']
    objects=UserManager()
    def __str__(self):
        return self.email
    def get_full_name(self):
        return self.email
    def get_short_name(self):
        return self.email
    def has_perm(self,perm,obj=None):
        return True
    def has_module_perms(self,app_label):
        return True
    @property
    def is_staff(self):
        return self.staff
    @property
    def is_superuser(self):
        return self.superuser

templates/base.html
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}
<!doctype html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Instituto Latinoamericano te da la bienvenida</title>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static '/base.css' %}"/>

    <body>
    <div class="container">
    <img src="{% static 'imgs/logo.png' %}" class="logo" alt="">
    <br>
  <nav class="navbar navbar-expand-xl bg-primary1 nav_container my-li mx-auto col-12">
     <div class="navbar-inner mx-auto">
          <button class="navbar-toggler" type="button" data-toggle="dropdown" data-target="#navbarsExample11" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse " id="navbarsExample11">
              <ul class="navbar-nav text-center ">
                <li class="nav-item ">
                    <a class=" nav-link" href="{% url 'index_view' %}"><h3>inicio</h3></a>
                </li>
                <li class="nav-item ">
                  <div class="dropdown">
                    <a class=" nav-link dropdown-toggle"  data-toggle="dropdown" href="{% url 'bachillerato' %}"><span class="caret"></span><h3>Bachillerato</h3></a>
                    <ul class="dropdown-menu bg-primary1">
    <li class=""><a href="{% url 'unoys' %}"class="   nav-link  my_form">1 año y 8 meses</a></li>
    <li><a href="{% url 'dosys' %}" class=" nav-link my_form">Dos años y medio</a></li>
    <li><a href="{% url 'unico' %}"class="  nav-link  my_form" >Examen único</a></li>
  </ul>
</div>
  </li>
                <li class="nav-item ">
                    <a class=" nav-link " href="{% url 'licenciaturas' %}"><h3>licenciaturas</h3></a>
                </li>
                  <li class="nav-item">
                      <a class=" nav-link" href="{% url 'especialidad' %}"><h3>Especialidades</h3></a>
                  </li>
                  <li class="nav-item">
                    {% if user.is_superuser %}
                    <div class="dropdown">
                       <a class=" nav-link dropdown-toggle" data-toggle="dropdown" href="{% url 'login' %}"><span class="caret"></span><h3>{{ request.user.email }}</h3></a>
                       <ul class="dropdown-menu bg-primary1">
                         <li class=""><a href="{% url 'register' %}"class="   nav-link  my_form">registrar alumno</a></li>
                         <li><a href="{% url 'logout' %}" class=" nav-link my_form">logout</a></li>
                       </div>
                    {% elif user.is_authenticated %}
                    <div class=" dropdown">
                       <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="{% url 'login' %}"><span class="caret"></span><h3>{{ request.user.email }}</h3></a>
                       <ul class="dropdown-menu bg-primary1">
                         <li class=""><a href="{% url 'calificaciones1' %}"class="   nav-link  my_form">calificaciones 1</a></li>
                         <li class=""><a href="{% url 'calificaciones2' %}"class="   nav-link    my_form">calificaciones 2</a></li>
                         <li class=""><a href="{% url 'calificaciones3' %}"class="   nav-link   my_form">calificaciones 3</a></li>
                         <li class=""><a href="{% url 'calificaciones4' %}"class="   nav-link  my_form">calificaciones 4</a></li>
                         <li class=""><a href="{% url 'calificaciones5' %}"class="   nav-link   my_form">calificaciones 5</a></li>
                         <li class=""><a href="{% url 'calificaciones6' %}"class="   nav-link   my_form">calificaciones 6</a></li>
                         <li class=""><a href="{% url 'all_cal' %}"class="   nav-link   my_form">historial academico</a></li>

                         <li><a href="{% url 'logout' %}" class=" nav-link my_form">logout</a></li>
                       </div>
                       {% else %}
                        <a class=" nav-link" href="{% url 'login' %}"><h3>login</h3></a>
                      {% endif %}
                  </li>
              </ul>
          </div>
      </div>
  </nav>
  <br>
  {% block base %}
  {% endblock %}

</body>

templates/carousel.html
{% load static %}
<link rel="stylesheet" href="{% static 'base.css' %}"/>

<div class="container">
<div id="carouselExampleIndicators" class="carousel slide mx-auto" data-ride="carousel">
    <ol class="carousel-indicators ">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner carousel1" role="listbox">
      <!-- Slide One - Set the background image for this slide in the line below -->
      <div class="carousel-item active">
          <img src="{% static 'imgs/carusel1.jpg' %}" class="my_slide">
      </div>
      <!-- Slide Two - Set the background image for this slide in the line below -->
      <!-- Slide Three - Set the background image for this slide in the line below -->
      <div class="carousel-item">
          <img src=" {% static 'imgs/carusel2.jpg' %}"  class="my_slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
</div>

templates/costos.html
{% extends 'base.html' %}
{% block base %}
{% include "carousel.html" %}
{% load static %}

<div class="container">

<div class="row bbbb">

<div class="col-12">
<h1>Beneficios y costos</h1>

<h3>Comprueba que somos una excelente opción:</h3>

· Tres modalidades distintas a elegir: 2 años y medio | 1 año 8 meses | Un examen
<br>
. Aplicación de exámenes en el plantel continuamente, para que refuerces constantemente tus conocimientos
<br>
· Certificación con validez oficial

<br>

· Desde 2 horas diarias o en sabatino, también tenemos modalidades de medio tiempo de 4 horas diarias

<br>

· Sin restricción de edad


<br>
· Sin examen de admisión


<br>
· Colegiaturas accesibles: $230.00 semanales en bachillerato de 2 años y medio (Turno vespertino); $250.00 semanales en bachillerato de 2 años y medio (Turno matutino); $300.00 semanales en bachillerato en 1 año 8 meses

<br>

· Clases de inglés e informática ¡Por la misma colegiatura!

<br>

· Grupos reducidos, máximo 12 alumnos

<br>

· Reinscripción anual, no pagas reinscripción cada trimestre


<br>
· No hay venta de libros ni bitácoras ni uniforme

<br>

· Sin promedio mínimo

<br>

· Si lo necesitas te ayudamos a certificar tus estudios de secundaria
<br>
</div>
</div>
</div>
{% include 'footer.html' %}
{% endblock %}

templates/dosys.html
{% extends 'base.html' %}
{% block base %}
{% include "carousel.html" %}
<div class="container">
  <div class="row">
    <div class="col-12 my_form">


<h1>Plan trimestral</h1>
</div>
</div>
<div class="row">


<div class="col-6 my_form">
<h3>Si recién egresaste de la secundaria o buscas una opción económica</h3>





Si recién egresaste de la secundaria o buscas algo económico está opción es para ti. Con éste plan de estudios te ayudamos a obtener un nivel académico de excelencia. Si tienes dudas de temas de la secundaria, si no entiendes o se te dificulta alguna materia, si crees que le escuela no es para ti o simplemente buscas una opción más accesible económicamente, te ofrecemos este plan.


</div>
<div class="col-6 my_form">
<h3>BENEFICIOS</h3>

. Aplicación de Examen en el Plantel
<br>
· Certificación con validez oficial (Centro de asesoría)
<br>
· Desde 2 horas diarias o en sabatino
<br>
· Sin restricción de edad
<br>
· Sin examen de admisión
<br>
· Todas las materias desde cero: corregimos problemas cualquier materia para prepararte para el ingreso a la universidad.
<br>
· Colegiaturas más bajas que en otros planes, más tiempo menor colegiatura. No pagues lo mismo si tardarás más tiempo en terminar.
<br>
· Clases de Ingles e informática por la misma colegiatura
<br>
· Grupos reducidos
<br>
· Reinscripción anual
<br>
· No hay venta de libros ni bitácoras
<br>
· Sin promedio mínimo
<br>
· Si lo necesitas te ayudamos a certificar tu secundaria
<br>
</div>
</div>
</div>
{% include 'footer.html' %}
 {% endblock %}

templates/especialidades.html
{% extends 'base.html' %}
{% block base %}
{% include "carousel.html" %}
{% load static %}
<div class="container">
  <div class="row">
    <div class="col-6 bbbb img_link">
        <br>
      <img src="{% static 'imgs/english.jpg' %}" alt=""/>

<h3>Inglés</h3>
Aprende y domina el idioma inglés!
<br>
Aprende inglés de una forma práctica y divertida.
<br>
* Habla desde la primera clase, practica con tus compañeros de clase.
<br>
* Maneja las 4 habilidades: Habla, Comprende, Escribe, Lee.
<br>
* ¿Te gusta la música? Aprende inglés y utiliza la música como herramienta, cada semana dominarás una canción distinta.
<br>
* Validez Oficial, por cada nivel, de 6 meses, recibe un diploma de la Secretaría de Educación Pública.
<br>
* Club de conversación. Participa en nuestro club de conversación, perfecciona tu pronunciación para que tus compañeros te entiendan, afina tu oido para comprender lo que tus compañeros tratan de decirte.
<br>
* Las colegiaturas son congeladas y si estudias tu bachillerato con nosotros, estudia inglés por sólo $50.oo pesos semanales.
<br>
</div>
<div class="col-6 bbbb img_link ">
  <br>
  <img src="{% static 'imgs/technology.jpg' %}" alt=""/>

<h3>Informática</h3>
<br>
Con validez oficial:
<br>
* Mantenimiento y reparación de equipos de cómputo
<br>
* Configuración y operación de sistemas operativos
<br>
* Manejo de procesador de textos
<br>
* Manejo de hoja de cálculo
<br>
* Manejo de bases de datos
<br>
Para estudios que no requieren de validez oficial:
<br>
* Diseño gráfico (vectores)
<br>
* Diseño gráfico (Mapa de bits)
<br>
* Edición de audio y video
<br>
* Paquetería contable (Contabilidad, Nóminas e Inventario)
<br>
* Lenguajes de programación
<br>
</div>
</div>
</div>
{% include "footer.html" %}
{% endblock %}

templates/footer.html
{% load static %}

<div class="container">
<div class="row ">
  <div class="col-12 bbbb footer-color ">
    <h3>Instituto Latinoamericano</h3>
<p>
Miguel Ángel de Quevedo 1084, primer piso.
<br>
Colonia Parque San Andrés, Coyoacán.
<br>
04040, Distrito Federal.
<br>
55-44-34-29
71-59-98-96
<br>
emediasuperior@hotmail.com
<br>
made by:Pablo Ramirez Vargas(thegreatperses@gmail.com)
</p>
  </div>
</div>

</div>

templates/index_view.html
{% extends  'base.html'  %}
{% block base %}
{% load static %}
{% include "carousel.html" %}
<div class="my_form ">
<div class="row">
  <div class="col-12">
  <h1>Instituto Latinoamericano<h1>
  <h4>
  <br>
  Te ofrecemos varias opciones para que concluyas tu bachillerato,
  las opciones difieren de acuerdo al tiempo y al costo,
  la elección depente completamente de ti, de tu economía
  y de tu necesidad de concluir el bachillerato.
  Todas las opciones incluyen inglés e informática sin costo.
  ¿Sabes en dónde estamos? <a>Da clic aquí</a>

  Tu colegiatura no aumenta cuando avanzas de trimestre</h4>
<br>
</div>
</div>
<div class="col-12">
<h3>Horario de atención de 9:00 a 14:00</h3>
</div>
<div class="row">


<div class="col-6 bbb">
<img src="{% static 'imgs/wat.png' %}"/>
</div>
<div class="col-6 bb">

<h4 class="bolder" >55-44-34-29</h4 >
<h4 class="bolder">55-3310-92-39</h4>
<a href="{% url 'costos' %}" class="btn bg-primary1 bbbb costosbtn">costos </a>
</div>
<br>
<br>
</div>
<div class="col-12 ">
  <h2>Bachillerato</h2>
  <hr>
</div>
<div class="row img_link">


<div class="col-4">
  <img src="{% static 'imgs/proximos.jpg' %}"/>
  <br>
<h3>Próximos inicios</h3>
<hr>
<p>
Iniciamos 20 de agosto | 25 de agosto en horario sabatino.
¿No estás de acuerdo con tu opción COMIPEMS? Trae tu comprobante y te hacemos un descuento en tu inscripción!
</p>
</div>
<div class="col-4">
  <img src="{% static 'imgs/valides.jpg' %}"/>
  <h3>Validez Oficial</h3>
  <hr>
  <p>
  Para tu tranquilidad, como centro de asesoría,
  contamos con el respaldo de instituciones con
   reconocimiento de Validez Oficial, muchos de
   nuestros alumnos han continuado sus estudios
   a nivel superior, da <a href="https://www.ilatinoamericano.com/historias-de-%C3%A9xito/">clic aquí</a> y compruébalo...
   </p>
</div>
<div class="col-4">
  <img src="{% static 'imgs/convenios.jpg' %}"/>
  <h3>Convenios con grupos</h3>

<hr>
<p>Cuando  existen  grupos,  en  empresas  u organizaciones
,interesados en cursar sus estudios les ofrecemos ventajas
 significativas en cualquiera de  nuestras  opciones  educativas.
Contacta  a nuestros  asesores  educativos  para  más información...
</p>
</div>
<div class="col-12 ">
  <h2>Licenciatura</h2>
    <hr>
</div>
</div>
<div class="row img_link">
  <div class="col-4">
    <img src="{% static 'imgs/licenciaturas.jpg' %}"/>
  <h3>Convenios con grupos</h3>
  <hr>
  <p>Cuando  existen  grupos,  en  empresas  u organizaciones
  ,interesados en cursar sus estudios les ofrecemos ventajas
   significativas en cualquiera de  nuestras  opciones  educativas.
  Contacta  a nuestros  asesores  educativos  para  más información...
  </p>
</div>
<div class="col-4">
  <img src="{% static 'imgs/tt.jpg' %}"/>
<h3>Ejerce mientras estudias</h3>
<hr>
<p>Como estudiante, participas en asesorías jurídicas,
  fiscales y pedagógicas al lado de tus profesores,
  de esta manera combinas la teoría y la práctica,
  adquieres experiencia antes de concluir tus estudios.
</p>
</div>
<div class="col-4">
  <img src="{% static 'imgs/acesores.jpg' %}"/>
<h3>Asesores educativos</h3>
<hr>
<p>Si alguno de nuestros asesores te visita
   no dudes en aprovechar los beneficios que
   te ofrece. Recuerda que ellos no
   hacen cobros de ningún tipo.
   No corras riesgos y comprueba los datos de tu asesor aquí...
</p>
</div>
</div>
  <div class="row">
    <div class="col-12 bbbb">
      <h2>Especialidades</h2>
        <hr>
    </div>

  </div>
<div class="row">

  <div class="col-6 bbbb">
    <a href="{% url 'especialidad' %}"><img src="{% static 'imgs/ingles.jpg' %}"/></a>
  <h3>Ingles</h3>
  <hr>
  <p>
Domina el idioma: obtén un mejor empleo, mejora tu calidad de vida, obtén acceso a mejores fuentes de información, aprende el idioma global!
  </p>
</div>
<div class="col-6 bbbb">
  <a href="{% url 'especialidad' %}"><img src="{% static 'imgs/informatica.jpg' %}"/></a>
<h3>Informática</h3>
<hr>
<p>
Domina el idioma: obtén un mejor empleo, mejora tu calidad de vida, obtén acceso a mejores fuentes de información, aprende el idioma global!
</p>
</div>
  </div>
</div>
{% include "messageform.html"%}
{% include 'footer.html' %}
{% endblock %}

templates/licenciaturas.html
{% extends 'base.html' %}
{% block base %}
{% include "carousel.html" %}
{% load static %}

<div class="container">
<div class="row">
<div class="col-12 bbbb">


<h2>Licenciaturas</h2>

<h3>Contabilidad - Derecho</h3>



Nuestras licenciaturas te preparan para que te incorpores al mercado laboral. Las clases son impartidas por profesionales que ejercen en sus respectivas áreas así que cada clase aprendes lo que se requiere para iniciar a trabajar. Todo a través de un equilibrio teórico práctico.



Terminas en 3 años 4 meses y la titulación es directa, no necesitas hacer tesis, servicio social o prácticas profesionales de manera obligatoria, pero puedes hacerlo si deseas practicar  en alguna institución. Si tienes experiencia laboral, o bien tus situación laboral te está presionando para titularte, podemos ofrecerte una modalidad a tu medida.



Además te ofrecemos los siguientes beneficios:<br>



     -Dos modalidades a elegir<br>
      -Titulación y certificación con validez oficial<br>
      -Cómodos horarios, sabatinos y próximamente vespertinos<br>
      -Sin restricción de edad<br>
      -Sin examen de admisión<br>
      -Titulación directa<br>
      -Grupos reducidos, máximo 12 aulumnos<br>
      -Reinscripción anual<br>
      -Sin promedio mínimo<br>
      -Si lo necesitas te ayudamos a certificar tus estudios de bachillerato<br>







Derecho: Su  objetivo  primordial  es  aplicar  el  marco  jurídico  vigente para lograr soluciones integrales  a  problemas  jurídicos,  con base  en  el  conocimiento,  interpretación  y aplicación de la ley.<br>


Contabilidad: Su propósito fundamental es formar contadores  con una amplia visión contable,  fiscal  y financiera, y que apliquen sus conocimientos en presupuestos y costos.<br>



</div>
</div>
</div>
{% include 'footer.html' %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block base %}
{% include 'carousel.html' %}
<div class="container">
  {% if user.is_authenticated %}
  <p>inicio de secion exitoso</p>
  {% else %}
  <div class="my_form">
<form method="post">
  {% csrf_token %}
{% for field in form %}
{{linebreaks}}
<h3>{{ field.label_tag }}</h3>
{{field}}
{{linebreaks}}
{% endfor %}
  <input type="submit" class="btn bg-primary1 btn-md" value="enviar">
  {{linebreaks}}
</form>
</div>
{% endif %}
</div>
{% include 'footer.html' %}
{% endblock %}

templates/messageform.html
<!--
<h1 class="my_form">Pide informes</h1>
<br>
            <h4 class="my_form">Nombre: *</h4>
            <br>
          <input type="text" name="nombre" maxlength="60" required id="id_nombre">
          <br>
            <h4 class="my_form">Curso o especialidad:</h4>
            <input type="text" class="form-control" id="exampleFormControlInput1" value="{{ form.curso.curso }}">
            <br>
          <h4 class="my_form">Dirección de e-mail: *</h4>
          <br>
           <input type="email" class="form-control" id="email"  value="{{ form.email.email }}" placeholder="name@example.com">
           <br>
          <h4 class="my_form">Teléfono: *</h4>

          <br>
          <input type="tel" class="form-control" id="telefono" value="{{ form.telefono.telefono }}">
          <br>
          <h4 class="my_form">Mensaje: *</h4>
          <br>
          <textarea class="form-control" id="body" rows="4" value="{{ form.body.body }}"></textarea>
          <br>
                <input type="submit" class="btn btn-primary btn-md" value="enviar">
</form>//-->
<div class="container">
<form method="post" action="/send_message/">
  {% csrf_token %}
{% for field in form %}
{{linebreaks}}
<h3 class="my_form">{{ field.label_tag }}</h3>
{{field}}
{{linebreaks}}
{% endfor %}
  <input type="submit" class="btn bg-primary1 btn-md" value="enviar">
</form>
</div>

templates/register.html
{% extends 'base.html' %}
{% block base %}
{% include "carousel.html" %}
{% load static %}

<form class="my_form" method="post">
  {% csrf_token %}
{{ my_user.as_p }}
{{ user_form.as_p }}
<input type="submit" name="" value="register">
</form>
{% include 'footer.html'%}
{% endblock %}

templates/thanks.html
{extends "base.html"}
<h1>tu mensage se a enviado</h1>

templates/unico.html
{% extends 'base.html' %}
{% block base %}
{% include "carousel.html" %}
{% load static %}
<div class="container">
  <div class="row">
    <div class="col-12 my_Form">
<h1>Intensivo</h1>
    </div>
    </div>
    <div class="row">
      <div class="col-6 my_form">
<h3>Si te urge concluir tu bachillerato...</h3>
si cursaste tus estudios de bachillerato pero no lograste certificar aquí está la solución. Concluyes en cuatro meses, te preparamos para que apruebes tu bachillerato en un sólo examen. Garantizado, no te arriesgues, no trunques tu vida académica, hoy tu bachillerato es importante, mañana lo será la universidad, no tomes una decisión equivocada.
      </div>
      <div class="col-6 my_form">
<h3>BENEFICIOS</h3>

BENEFICIOS
. Aplicación de Examen en el Plantel
<br>
· Certificación con validez oficial
<br>
· Desde 2 horas diarias o en sabatino
<br>
· Mayores de edad
<br>
· Sin examen de admisión
<br>
· Grupos reducidos
<br>
· No hay venta de libros ni bitácoras
<br>

· Sin promedio mínimo
<br>
· Garantizado
<br>
      </div>
    </div>
  </div>









{% include 'footer.html' %}
{% endblock %}

templates/unoys.html
{% extends 'base.html' %}
{% block base %}
{% include "carousel.html" %}
{% load static %}
<div class="container">
<div class="row">
<div class="col-12 bbbb">


  <h1>Plan trimestral</h1>

</div>
<br>
</div>
<div class="row">

<div class="col-6 my_form">


<h3>La mejor opción costo-tiempo </h3>





Concluyes tu bachillerato en 6 trimestres.
<br>
Si necesitas recuperar tiempo perdido te recomendamos esta opción;
<br>
no sólo terminas más rápido, también adquieres los conocimientos necesarios para el ingreso a la universidad.
<br>
</div>

<div class="col-6 my_form">


<h3>BENEFICIOS</h3>



. Aplicación de Examen en el Plantel
<br>
· Certificación con validez oficial expedida por la Secretaría de Educación Pública (Centro de asesoría)
<br>
· Desde 2 horas diarias o en horario sabatino
<br>
· Sin restricción de edad
<br>
· Sin examen de admisión
<br>
· Sin promedio mínimo
<br>
· Colegiaturas accesibles
<br>
· Clases de Ingles
<br>
· Grupos reducidos
<br>
· Reinscripción anual, no pagas reinscripción cada trimestre
<br>
· No hay venta de libros ni bitácoras
<br>
· Si lo necesitas te ayudamos a certificar tu secundaria
<br>
 </div>
 </div>
</div>
{% include 'footer.html'%}
{% endblock %}